version: "2"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=nopasswordhaha
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=db-username
    volumes:
      - ../database:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - database
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - DATABASE_USERNAME=db-username
      - DATABASE_PASSWORD=nopasswordhaha
    ports:
      - "8080:8080"